version: 2.1

jobs:
  # Build terraform image into Docker Hub.
  build-terraform:
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          cd dockerImages/terraform
          TAG=latest
          docker build -t $DOCKER_USER/terraform:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/terraform

  # Build CircleCI Runner image into Docker Hub.
  build-circleciRunner:
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          cd dockerImages/circleciRunner
          TAG=latest
          docker build -t $DOCKER_USER/circleci-runner:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/circleci-runner

  # Build CircleCI Runner image into Docker Hub.
  build-alpineSlackNotifications:
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          cd dockerImages/alpineSlackNotifications
          TAG=latest
          docker build -t $DOCKER_USER/alpine-slack-notifications:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/alpine-slack-notifications

  # Build Graph As Code image into Docker Hub.
  build-graphAsCodeCi:
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          cd dockerImages/graphAsCodeCi
          TAG=latest
          docker build -t $DOCKER_USER/graph-as-code-ci:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/graph-as-code-ci

workflows:
  build-and-deploy:
    jobs:
      # Deploy terraform image
      - build-terraform:
          context: docker-images
          filters:
            branches:
              only: main
      # Deploy CircleCI Runner image
      - build-circleciRunner:
          context: docker-images
          filters:
            branches:
              only: main
      # Deploy Alpine Slack Notifications image
      - build-alpineSlackNotifications:
          context: docker-images
          filters:
            branches:
              only: main
      # Deploy Graph As Code CI image
      - build-graphAsCodeCi:
          context: docker-images
          filters:
            branches:
              only: main
